# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FixedCost-App' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FixedCost-App

pod 'IQKeyboardManagerSwift', '6.3.0'

  target 'FixedCost-AppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'FixedCost-AppUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
